---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl python-pip python-apt gcc

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts site.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i hosts site.yml --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i hosts site.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
